/**
 * @packageDocumentation
 * @module api.functional.bbs.articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Format } from "typia/lib/tags/Format";

import type { IBbsArticle } from "../../../structures/bbs/IBbsArticle";
import type { IPage } from "../../../structures/common/IPage";

/**
 * List up entire articles, but paginated and summarized.
 *
 * This method is for listing up summarized articles with pagination.
 *
 * If you want, you can search and sort articles with specific conditions.
 *
 * @param props.section Target section
 * @param props.body Pagination request info with searching and sorting options
 * @returns Paginated articles with summarization
 *
 * @controller BbsArticlesController.index
 * @path PATCH /bbs/articles/:section
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Output> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          template: index.METADATA.path,
          path: index.path(props),
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Target section
     */
    section: string;

    /**
     * Pagination request info with searching and sorting options
     */
    body: Body;
  };
  export type Body = IBbsArticle.IRequest;
  export type Output = IPage<IBbsArticle.ISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/bbs/articles/:section",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/bbs/articles/${encodeURIComponent(props.section?.toString() ?? "null")}`;
  export const random = (): IPage<IBbsArticle.ISummary> =>
    typia.random<IPage<IBbsArticle.ISummary>>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("section")(() => typia.assert(props.section));
    assert.body(() => typia.assert(props.body));
    return random();
  };
}

/**
 * Get an article with detailed info.
 *
 * Open an article with detailed info, increasing reading count.
 *
 * @param props.section Target section
 * @param props.id Target articles id
 * @returns Detailed article info
 *
 * @controller BbsArticlesController.at
 * @path GET /bbs/articles/:section/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Output> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        template: at.METADATA.path,
        path: at.path(props),
      });
}
export namespace at {
  export type Props = {
    /**
     * Target section
     */
    section: string;

    /**
     * Target articles id
     */
    id: string;
  };
  export type Output = IBbsArticle;

  export const METADATA = {
    method: "GET",
    path: "/bbs/articles/:section/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/bbs/articles/${encodeURIComponent(props.section?.toString() ?? "null")}/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): IBbsArticle => typia.random<IBbsArticle>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("section")(() => typia.assert(props.section));
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * Create a new article.
 *
 * Create a new article and returns its detailed record info.
 *
 * @param props.section Target section
 * @param props.body New article info
 * @returns Newly created article info
 *
 * @controller BbsArticlesController.create
 * @path POST /bbs/articles/:section
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(props),
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Target section
     */
    section: string;

    /**
     * New article info
     */
    body: Body;
  };
  export type Body = IBbsArticle.ICreate;
  export type Output = IBbsArticle;

  export const METADATA = {
    method: "POST",
    path: "/bbs/articles/:section",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/bbs/articles/${encodeURIComponent(props.section?.toString() ?? "null")}`;
  export const random = (): IBbsArticle => typia.random<IBbsArticle>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("section")(() => typia.assert(props.section));
    assert.body(() => typia.assert(props.body));
    return random();
  };
}

/**
 * Update article.
 *
 * When updating, this BBS system does not overwrite the content, but accumulate it.
 * Therefore, whenever an article being updated, length of {@link IBbsArticle.snapshots}
 * would be increased and accumulated.
 *
 * @param props.section Target section
 * @param props.id Target articles id
 * @param props.body Content to update
 * @returns Newly created content info
 *
 * @controller BbsArticlesController.update
 * @path PUT /bbs/articles/:section/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(props),
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Target section
     */
    section: string;

    /**
     * Target articles id
     */
    id: string & Format<"uuid">;

    /**
     * Content to update
     */
    body: Body;
  };
  export type Body = IBbsArticle.IUpdate;
  export type Output = IBbsArticle.ISnapshot;

  export const METADATA = {
    method: "PUT",
    path: "/bbs/articles/:section/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/bbs/articles/${encodeURIComponent(props.section?.toString() ?? "null")}/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): IBbsArticle.ISnapshot =>
    typia.random<IBbsArticle.ISnapshot>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("section")(() => typia.assert(props.section));
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.body));
    return random();
  };
}

/**
 * Erase an article.
 *
 * Erase an article with specific password.
 *
 * @param props.section Target section
 * @param props.id Target articles id
 * @param props.body Password to erase
 *
 * @controller BbsArticlesController.erase
 * @path DELETE /bbs/articles/:section/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          template: erase.METADATA.path,
          path: erase.path(props),
        },
        props.body,
      );
}
export namespace erase {
  export type Props = {
    /**
     * Target section
     */
    section: string;

    /**
     * Target articles id
     */
    id: string;

    /**
     * Password to erase
     */
    body: Body;
  };
  export type Body = IBbsArticle.IErase;

  export const METADATA = {
    method: "DELETE",
    path: "/bbs/articles/:section/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/bbs/articles/${encodeURIComponent(props.section?.toString() ?? "null")}/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("section")(() => typia.assert(props.section));
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.body));
    return random();
  };
}
