version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@nestjs/*"
      - dependency-name: "@nestia/*"
      - dependency-name: "nestia"
      - dependency-name: "tgrid"
      - dependency-name: "tstl"
      - dependency-name: "typia"
      - dependency-name: "typescript"
      - dependency-name: "ttsc"
      - dependency-name: "@ttsc/*"
    groups:
      Samchon:
        patterns:
          - "@nestia/*"
          - "nestia"
          - "tgrid"
          - "tstl"
          - "typia"
      NestJS:
        patterns:
          - "@nestjs/*"
      TypeScript:
        patterns:
          - "typescript"
          - "ttsc"
          - "@ttsc/*"
