name: build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        working-directory: packages/backend
        run: pnpm test --simultaneous 16
